"""Map Pydantic AI streaming events into Conductor event payloads.

This module holds the bridge between Pydantic AI's event stream and
Conductor's ``EventCallback`` payloads.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable
from typing import Any

from pydantic_ai import Agent
from pydantic_ai.messages import (
    FunctionToolCallEvent,
    FunctionToolResultEvent,
    OutputToolResultEvent,
    PartDeltaEvent,
    PartStartEvent,
    RetryPromptPart,
    TextPart,
    TextPartDelta,
    ThinkingPart,
    ThinkingPartDelta,
    ToolCallPart,
)

from conductor.mcp.manager import FS_HINT, GENERIC_HINT, TRUNCATION_MARKER_PREFIX
from conductor.providers._event_format import (
    emit_parse_recovery_event,
    extract_tool_result_text,
    format_tool_arguments,
)

EventCallback = Callable[[str, dict[str, Any]], None]

logger = logging.getLogger(__name__)


def emit_output_recovery_event(
    event: Any,
    event_callback: EventCallback | None,
    *,
    attempt: int,
    max_attempts: int,
) -> bool:
    """Emit parse recovery metadata for an output-tool retry event."""
    if not isinstance(event, OutputToolResultEvent) or not isinstance(event.part, RetryPromptPart):
        return False

    content = event.part.content
    is_schema_failure = not (
        isinstance(content, list) and any(error.get("type") == "json_invalid" for error in content)
    )
    emit_parse_recovery_event(
        event_callback,
        attempt=attempt,
        max_attempts=max_attempts,
        is_schema_failure=is_schema_failure,
        error=event.part.model_response(),
    )
    return True


def _parse_truncation_marker(result: Any) -> dict[str, Any] | None:
    """Parse truncation metadata from the marker appended to a result.

    Mirrors ``ClaudeProvider._parse_truncation_marker`` so that Pydantic AI
    tool results can emit ``agent_tool_output_truncated`` with the same
    payload shape. The marker is generated by ``MCPManager._maybe_truncate_response``
    and always has the form::

        [output truncated: {original} chars -> {kept} kept{; optional path}. {HINT}]

    Args:
        result: The possibly truncated tool result. Non-string values are ignored.

    Returns:
        A dict with ``original_chars``, ``kept_chars``, and ``spill_path``
        (``None`` when the marker omits a path), or ``None`` when the
        result is not truncated.
    """
    if not isinstance(result, str) or not result:
        return None

    tail_window = 8192
    if TRUNCATION_MARKER_PREFIX not in result[-tail_window:]:
        return None

    tail = result[-tail_window:]
    match = re.search(
        r".*"
        + re.escape(TRUNCATION_MARKER_PREFIX)
        + r"\s*(\d+)\s*chars\s*->\s*(\d+)\s*kept"
        + r"(?:;\s*full output saved to:\s*(.+?))?\."
        + r"\s*"
        + r"(?:"
        + re.escape(GENERIC_HINT)
        + r"|"
        + re.escape(FS_HINT)
        + r")"
        + r"\]\s*$",
        tail,
        re.DOTALL,
    )

    if not match:
        return None

    original_chars = int(match.group(1))
    kept_chars = int(match.group(2))
    spill_path = match.group(3).strip() if match.group(3) else None

    return {
        "original_chars": original_chars,
        "kept_chars": kept_chars,
        "spill_path": spill_path,
    }


def _extract_tool_call_args(call: ToolCallPart) -> dict[str, Any] | None:
    """Return tool-call arguments as a dict, or None if empty/absent."""
    args = call.args_as_dict() if call.args else None
    if not args:
        return None
    return args


def map_pydantic_event(
    agent: Agent[Any, Any],
    event: Any,
) -> tuple[str, dict[str, Any]] | None:
    """Translate a Pydantic AI event into a Conductor event tuple.

    Handles streaming model-response events (``PartStartEvent`` for full
    parts, ``PartDeltaEvent`` for deltas) and response-handling tool events
    (``FunctionToolCallEvent`` / ``FunctionToolResultEvent``). ``agent_name``
    is derived from the Pydantic AI agent's configured ``name`` so the
    downstream ``EventCallback`` receives the same shape used by the other
    providers.

    Args:
        agent: The Pydantic AI agent that produced the event. Its ``name`` is
            used for the ``agent_name`` payload key.
        event: A Pydantic AI event (``AgentStreamEvent`` or
            ``HandleResponseEvent``).

    Returns:
        A tuple ``(event_type, data_dict)`` for Conductor, or ``None`` if
        the event should be ignored.
    """
    agent_name = agent.name or "agent"

    if isinstance(event, PartStartEvent):
        part = event.part
        if isinstance(part, TextPart) and part.content:
            return ("agent_message", {"agent_name": agent_name, "content": part.content})
        if isinstance(part, ThinkingPart) and part.content:
            return ("agent_reasoning", {"agent_name": agent_name, "content": part.content})
        return None

    if isinstance(event, PartDeltaEvent):
        delta = event.delta
        if isinstance(delta, TextPartDelta) and delta.content_delta:
            return ("agent_message", {"agent_name": agent_name, "content": delta.content_delta})
        if isinstance(delta, ThinkingPartDelta) and delta.content_delta:
            return ("agent_reasoning", {"agent_name": agent_name, "content": delta.content_delta})
        return None

    if isinstance(event, FunctionToolCallEvent):
        call = event.part
        return (
            "agent_tool_start",
            {
                "agent_name": agent_name,
                "tool_name": call.tool_name,
                "arguments": format_tool_arguments(_extract_tool_call_args(call)),
            },
        )

    if isinstance(event, FunctionToolResultEvent):
        call = event.part
        result_text = extract_tool_result_text(call.content)
        return (
            "agent_tool_complete",
            {
                "agent_name": agent_name,
                "tool_name": call.tool_name,
                "result": result_text,
            },
        )

    return None


def emit_pydantic_event(
    agent: Agent[Any, Any],
    event: Any,
    event_callback: EventCallback | None,
) -> None:
    """Map a Pydantic AI event and emit it through a Conductor callback.

    Callback errors are swallowed with a debug log so subscribers can never
    crash the agent loop.

    Args:
        agent: The Pydantic AI agent that produced the event.
        event: A Pydantic AI event to map and forward.
        event_callback: Optional Conductor event callback. If ``None``, the
            event is silently dropped.
    """
    if event_callback is None:
        return

    mapped = map_pydantic_event(agent, event)
    if mapped is None:
        return

    event_type, data = mapped
    try:
        event_callback(event_type, data)
    except Exception:
        logger.debug("Error in event_callback for %s", event_type, exc_info=True)


def emit_compaction_config(
    event_callback: EventCallback | None,
    *,
    agent_name: str,
    model: str,
    context_window: int,
    context_window_source: str,
    output_limit: int,
    output_limit_source: str,
    enabled: bool,
    trigger_tokens: int | None,
    target_tokens: int | None,
    tool_buffer: int,
    effective_tool_buffer: int | None,
    disabled_reason: str | None = None,
) -> None:
    """Emit an ``agent_compaction_config`` event, swallowing callback errors.

    This informational event fires once per agent execution, immediately after
    the resolved context-window and output-limit values are known. It is
    emitted whether or not compaction is enabled so operators can read the
    resolved thresholds — or, for a disabled plan, the reason it is off —
    from the event log. ``trigger_tokens``/``target_tokens`` are ``None``
    (serialized as null) when compaction is disabled; ``effective_tool_buffer``
    is the window-fraction-clamped reserve the plan actually applied, and is
    ``None`` only when the plan carries no buffer information.
    """
    if event_callback is None:
        return

    try:
        event_callback(
            "agent_compaction_config",
            {
                "agent_name": agent_name,
                "model": model,
                "context_window": context_window,
                "context_window_source": context_window_source,
                "output_limit": output_limit,
                "output_limit_source": output_limit_source,
                "enabled": enabled,
                "disabled_reason": disabled_reason,
                "trigger_tokens": trigger_tokens,
                "target_tokens": target_tokens,
                "tool_buffer": tool_buffer,
                "effective_tool_buffer": effective_tool_buffer,
            },
        )
    except Exception:
        logger.debug("Error in event_callback for agent_compaction_config", exc_info=True)


def emit_agent_turn_start(
    event_callback: EventCallback | None,
    turn: int | str,
) -> None:
    """Emit an ``agent_turn_start`` event, swallowing callback errors.

    Conductor expects ``{"turn": "awaiting_model"}`` immediately before
    each model API call and ``{"turn": N}`` at the start of each agentic-loop
    iteration. This helper lets the provider loop drive both without
    duplicating the error-swallowing logic.

    Args:
        event_callback: Optional Conductor event callback. If ``None``, the
            event is silently dropped.
        turn: Either the integer iteration number or the string
            ``"awaiting_model"``.
    """
    if event_callback is None:
        return

    try:
        event_callback("agent_turn_start", {"turn": turn})
    except Exception:
        logger.debug("Error in event_callback for agent_turn_start", exc_info=True)


def maybe_emit_tool_truncation(
    agent: Agent[Any, Any],
    tool_name: str,
    result: Any,
    event_callback: EventCallback | None,
) -> None:
    """Emit ``agent_tool_output_truncated`` if a tool result is truncated.

    ``MCPManager`` appends a plain-text marker to oversized results, but the
    Pydantic AI adapter does not parse it. This helper detects the marker and
    forwards the structured truncation event to subscribers with the same
    payload keys used by ``ClaudeProvider``.

    Args:
        agent: The Pydantic AI agent that produced the tool result.
        tool_name: Name of the tool whose output was truncated.
        result: The raw tool result string returned by the tool call.
        event_callback: Optional Conductor event callback. If ``None``, the
            check is skipped.
    """
    if event_callback is None:
        return

    truncation_info = _parse_truncation_marker(result)
    if truncation_info is None:
        return

    agent_name = agent.name or "agent"
    try:
        event_callback(
            "agent_tool_output_truncated",
            {
                "agent_name": agent_name,
                "tool_name": tool_name,
                "original_chars": truncation_info["original_chars"],
                "kept_chars": truncation_info["kept_chars"],
                "spill_path": truncation_info["spill_path"],
            },
        )
    except Exception:
        logger.debug("Error in event_callback for agent_tool_output_truncated", exc_info=True)


def emit_compaction_start(
    event_callback: EventCallback | None,
    *,
    agent_name: str,
    strategy: str,
    model: str,
    context_window: int,
    context_window_source: str,
    output_limit: int,
    output_limit_source: str,
    trigger_tokens: int,
    target_tokens: int,
    messages_before: int,
    tokens_before: int,
    trigger_reason: str = "trigger",
    density_tokens: int | None = None,
) -> None:
    """Emit an ``agent_compaction_start`` event, swallowing callback errors.

    This event fires immediately before compaction begins. ``trigger_reason``
    names the gate that fired: ``"trigger"`` when the primary token estimate
    exceeded the reserve-based trigger threshold, or ``"window_guard"`` when
    the density-calibrated safety estimate reached the known context window
    (which can happen well below the trigger on token-dense content).
    ``tokens_before`` is always the primary-scale token estimate; the
    density-calibrated value that fired the window guard is reported
    separately as ``density_tokens`` (``None`` when that measurement was
    unavailable).
    """
    if event_callback is None:
        return

    try:
        event_callback(
            "agent_compaction_start",
            {
                "agent_name": agent_name,
                "strategy": strategy,
                "model": model,
                "context_window": context_window,
                "context_window_source": context_window_source,
                "output_limit": output_limit,
                "output_limit_source": output_limit_source,
                "trigger_tokens": trigger_tokens,
                "target_tokens": target_tokens,
                "messages_before": messages_before,
                "tokens_before": tokens_before,
                "trigger_reason": trigger_reason,
                "density_tokens": density_tokens,
            },
        )
    except Exception:
        logger.debug("Error in event_callback for agent_compaction_start", exc_info=True)


def emit_compaction_complete(
    event_callback: EventCallback | None,
    *,
    agent_name: str,
    strategy: str,
    model: str,
    context_window: int,
    context_window_source: str,
    messages_before: int,
    messages_after: int,
    tokens_before: int,
    tokens_after: int,
    elapsed: float,
    degraded_tiers: list[str],
    still_over_trigger: bool,
    degraded_estimators: list[str] | None = None,
    still_over_window: bool = False,
) -> None:
    """Emit a success-shaped ``agent_compaction_complete`` event.

    This event fires after compaction finishes, regardless of which tier
    produced the final context. ``degraded_tiers`` names the tiers whose own
    ``compact`` raised and were skipped (recovered by a later tier), and
    ``still_over_trigger`` reports that the post-compaction estimate remains
    above the trigger, so consumers can distinguish a full success from a
    degraded outcome instead of reading both as false success.
    ``degraded_estimators`` names the measurements that were lost before
    compaction ran — ``"primary"`` when the token gate fell back to the
    density-calibrated estimate, ``"density"`` when the window guard was
    disarmed for the request. ``still_over_window`` reports that a
    window-guard compaction could not bring the density-calibrated estimate
    back below the known context window — the request may still be rejected
    by the provider.
    """
    if event_callback is None:
        return

    try:
        event_callback(
            "agent_compaction_complete",
            {
                "agent_name": agent_name,
                "strategy": strategy,
                "model": model,
                "context_window": context_window,
                "context_window_source": context_window_source,
                "messages_before": messages_before,
                "messages_after": messages_after,
                "tokens_before": tokens_before,
                "tokens_after": tokens_after,
                "tokens_saved": max(0, tokens_before - tokens_after),
                "elapsed": elapsed,
                "errored": False,
                "degraded_tiers": degraded_tiers,
                "still_over_trigger": still_over_trigger,
                "degraded_estimators": degraded_estimators or [],
                "still_over_window": still_over_window,
            },
        )
    except Exception:
        logger.debug("Error in event_callback for agent_compaction_complete", exc_info=True)


def emit_compaction_complete_error(
    event_callback: EventCallback | None,
    *,
    agent_name: str,
    strategy: str,
    model: str,
    exc: Exception,
    context_window: int | None = None,
    context_window_source: str | None = None,
    messages_before: int | None = None,
    tokens_before: int | None = None,
) -> None:
    """Emit an errored ``agent_compaction_complete`` event, swallowing callback errors.

    This event fires when compaction itself fails and the request context is
    being returned unchanged. Any before-metrics that are known are included
    alongside the error details.
    """
    if event_callback is None:
        return

    payload: dict[str, Any] = {
        "agent_name": agent_name,
        "strategy": strategy,
        "model": model,
        "errored": True,
        "error_type": type(exc).__name__,
        "message": str(exc),
    }
    if context_window is not None:
        payload["context_window"] = context_window
    if context_window_source is not None:
        payload["context_window_source"] = context_window_source
    if messages_before is not None:
        payload["messages_before"] = messages_before
    if tokens_before is not None:
        payload["tokens_before"] = tokens_before

    try:
        event_callback("agent_compaction_complete", payload)
    except Exception:
        logger.debug("Error in event_callback for agent_compaction_complete", exc_info=True)


def emit_compaction_skipped(
    event_callback: EventCallback | None,
    *,
    agent_name: str,
    strategy: str,
    model: str,
    reason: str,
) -> None:
    """Emit an ``agent_compaction_skipped`` event, swallowing callback errors.

    This event fires when compaction did not run for a reason other than the
    gate staying below its thresholds — currently only
    ``reason="estimate_unavailable"``, when both the primary and the fallback
    context measurements failed. It exists so a silently skipped safety gate
    is visible in the JSONL log and dashboard instead of being
    indistinguishable from a request that simply needed no compaction.
    """
    if event_callback is None:
        return

    try:
        event_callback(
            "agent_compaction_skipped",
            {
                "agent_name": agent_name,
                "strategy": strategy,
                "model": model,
                "reason": reason,
            },
        )
    except Exception:
        logger.debug("Error in event_callback for agent_compaction_skipped", exc_info=True)
